/**
 * This class is generated by jOOQ
 */
package com.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Information extends org.jooq.impl.TableImpl<com.jooq.tables.records.InformationRecord> {

	private static final long serialVersionUID = -2143264691;

	/**
	 * The reference instance of <code>applications.information</code>
	 */
	public static final com.jooq.tables.Information INFORMATION = new com.jooq.tables.Information();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.jooq.tables.records.InformationRecord> getRecordType() {
		return com.jooq.tables.records.InformationRecord.class;
	}

	/**
	 * The column <code>applications.information.company</code>.
	 */
	public final org.jooq.TableField<com.jooq.tables.records.InformationRecord, java.lang.String> COMPANY = createField("company", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>applications.information.position</code>.
	 */
	public final org.jooq.TableField<com.jooq.tables.records.InformationRecord, java.lang.String> POSITION = createField("position", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>applications.information.location</code>.
	 */
	public final org.jooq.TableField<com.jooq.tables.records.InformationRecord, java.lang.String> LOCATION = createField("location", org.jooq.impl.SQLDataType.VARCHAR.length(25), this, "");

	/**
	 * The column <code>applications.information.dateApplied</code>.
	 */
	public final org.jooq.TableField<com.jooq.tables.records.InformationRecord, java.sql.Date> DATEAPPLIED = createField("dateApplied", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>applications.information.contactName</code>.
	 */
	public final org.jooq.TableField<com.jooq.tables.records.InformationRecord, java.lang.String> CONTACTNAME = createField("contactName", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>applications.information.contactMethod</code>.
	 */
	public final org.jooq.TableField<com.jooq.tables.records.InformationRecord, java.lang.String> CONTACTMETHOD = createField("contactMethod", org.jooq.impl.SQLDataType.VARCHAR.length(25), this, "");

	/**
	 * The column <code>applications.information.contactedMeFirst</code>.
	 */
	public final org.jooq.TableField<com.jooq.tables.records.InformationRecord, java.lang.String> CONTACTEDMEFIRST = createField("contactedMeFirst", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "");

	/**
	 * The column <code>applications.information.status</code>.
	 */
	public final org.jooq.TableField<com.jooq.tables.records.InformationRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(6), this, "");

	/**
	 * The column <code>applications.information.notes</code>.
	 */
	public final org.jooq.TableField<com.jooq.tables.records.InformationRecord, java.lang.String> NOTES = createField("notes", org.jooq.impl.SQLDataType.VARCHAR.length(512), this, "");

	/**
	 * Create a <code>applications.information</code> table reference
	 */
	public Information() {
		this("information", null);
	}

	/**
	 * Create an aliased <code>applications.information</code> table reference
	 */
	public Information(java.lang.String alias) {
		this(alias, com.jooq.tables.Information.INFORMATION);
	}

	private Information(java.lang.String alias, org.jooq.Table<com.jooq.tables.records.InformationRecord> aliased) {
		this(alias, aliased, null);
	}

	private Information(java.lang.String alias, org.jooq.Table<com.jooq.tables.records.InformationRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.jooq.Applications.APPLICATIONS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.jooq.tables.Information as(java.lang.String alias) {
		return new com.jooq.tables.Information(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.jooq.tables.Information rename(java.lang.String name) {
		return new com.jooq.tables.Information(name, null);
	}
}
