/**
 * This class is generated by jOOQ
 */
package com.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Applications extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1626433728;

	/**
	 * The reference instance of <code>applications</code>
	 */
	public static final Applications APPLICATIONS = new Applications();

	/**
	 * No further instances allowed
	 */
	private Applications() {
		super("applications");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.jooq.tables.Information.INFORMATION);
	}
}
