/*
 * This file is generated by jOOQ.
*/
package com.jooq;


import com.jooq.tables.Information;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Applications extends SchemaImpl {

    private static final long serialVersionUID = -1099727523;

    /**
     * The reference instance of <code>applications</code>
     */
    public static final Applications APPLICATIONS = new Applications();

    /**
     * The table <code>applications.information</code>.
     */
    public final Information INFORMATION = com.jooq.tables.Information.INFORMATION;

    /**
     * No further instances allowed
     */
    private Applications() {
        super("applications", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Information.INFORMATION);
    }
}
