/*
 * This file is generated by jOOQ.
*/
package com.jooq;


import com.jooq.tables.Information;
import com.jooq.tables.records.InformationRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>applications</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<InformationRecord, Integer> IDENTITY_INFORMATION = Identities0.IDENTITY_INFORMATION;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<InformationRecord> KEY_INFORMATION_PRIMARY = UniqueKeys0.KEY_INFORMATION_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<InformationRecord, Integer> IDENTITY_INFORMATION = Internal.createIdentity(Information.INFORMATION, Information.INFORMATION.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<InformationRecord> KEY_INFORMATION_PRIMARY = Internal.createUniqueKey(Information.INFORMATION, "KEY_information_PRIMARY", Information.INFORMATION.ID);
    }
}
