/*
 * This file is generated by jOOQ.
*/
package com.jooq;


import com.jooq.tables.Information;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in applications
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>applications.information</code>.
     */
    public static final Information INFORMATION = com.jooq.tables.Information.INFORMATION;
}
