/**
 * This class is generated by jOOQ
 */
package com.jooq;

/**
 * Convenience access to all tables in applications
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table applications.information
	 */
	public static final com.jooq.tables.Information INFORMATION = com.jooq.tables.Information.INFORMATION;
}
