/**
 * This class is generated by jOOQ
 */
package com.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationRecord extends org.jooq.impl.TableRecordImpl<com.jooq.tables.records.InformationRecord> implements org.jooq.Record9<java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -2029806427;

	/**
	 * Setter for <code>applications.information.company</code>.
	 */
	public void setCompany(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>applications.information.company</code>.
	 */
	public java.lang.String getCompany() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>applications.information.position</code>.
	 */
	public void setPosition(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>applications.information.position</code>.
	 */
	public java.lang.String getPosition() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>applications.information.location</code>.
	 */
	public void setLocation(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>applications.information.location</code>.
	 */
	public java.lang.String getLocation() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>applications.information.dateApplied</code>.
	 */
	public void setDateapplied(java.sql.Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>applications.information.dateApplied</code>.
	 */
	public java.sql.Date getDateapplied() {
		return (java.sql.Date) getValue(3);
	}

	/**
	 * Setter for <code>applications.information.contactName</code>.
	 */
	public void setContactname(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>applications.information.contactName</code>.
	 */
	public java.lang.String getContactname() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>applications.information.contactMethod</code>.
	 */
	public void setContactmethod(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>applications.information.contactMethod</code>.
	 */
	public java.lang.String getContactmethod() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>applications.information.contactedMeFirst</code>.
	 */
	public void setContactedmefirst(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>applications.information.contactedMeFirst</code>.
	 */
	public java.lang.String getContactedmefirst() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>applications.information.status</code>.
	 */
	public void setStatus(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>applications.information.status</code>.
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>applications.information.notes</code>.
	 */
	public void setNotes(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>applications.information.notes</code>.
	 */
	public java.lang.String getNotes() {
		return (java.lang.String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.jooq.tables.Information.INFORMATION.COMPANY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.jooq.tables.Information.INFORMATION.POSITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.jooq.tables.Information.INFORMATION.LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field4() {
		return com.jooq.tables.Information.INFORMATION.DATEAPPLIED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.jooq.tables.Information.INFORMATION.CONTACTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.jooq.tables.Information.INFORMATION.CONTACTMETHOD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.jooq.tables.Information.INFORMATION.CONTACTEDMEFIRST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.jooq.tables.Information.INFORMATION.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.jooq.tables.Information.INFORMATION.NOTES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getCompany();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getPosition();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getLocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value4() {
		return getDateapplied();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getContactname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getContactmethod();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getContactedmefirst();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getNotes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InformationRecord value1(java.lang.String value) {
		setCompany(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InformationRecord value2(java.lang.String value) {
		setPosition(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InformationRecord value3(java.lang.String value) {
		setLocation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InformationRecord value4(java.sql.Date value) {
		setDateapplied(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InformationRecord value5(java.lang.String value) {
		setContactname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InformationRecord value6(java.lang.String value) {
		setContactmethod(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InformationRecord value7(java.lang.String value) {
		setContactedmefirst(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InformationRecord value8(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InformationRecord value9(java.lang.String value) {
		setNotes(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InformationRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.sql.Date value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached InformationRecord
	 */
	public InformationRecord() {
		super(com.jooq.tables.Information.INFORMATION);
	}

	/**
	 * Create a detached, initialised InformationRecord
	 */
	public InformationRecord(java.lang.String company, java.lang.String position, java.lang.String location, java.sql.Date dateapplied, java.lang.String contactname, java.lang.String contactmethod, java.lang.String contactedmefirst, java.lang.String status, java.lang.String notes) {
		super(com.jooq.tables.Information.INFORMATION);

		setValue(0, company);
		setValue(1, position);
		setValue(2, location);
		setValue(3, dateapplied);
		setValue(4, contactname);
		setValue(5, contactmethod);
		setValue(6, contactedmefirst);
		setValue(7, status);
		setValue(8, notes);
	}
}
